<?php
declare(strict_types=1);
require_once __DIR__ . "/../../includes/seguridad.php";
exigirAdmin();
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);if(!$id||$id<=0){header('Location: temas.php');exit;}
function recursoIcon(string $tipo):string{return match(strtolower($tipo)){ 'video'=>'bi-play-circle-fill','pdf'=>'bi-file-earmark-pdf-fill','juego'=>'bi-controller','simulador'=>'bi-display','app'=>'bi-phone','presentacion'=>'bi-easel2-fill','articulo'=>'bi-file-text-fill','blog'=>'bi-journal-text',default=>'bi-link-45deg'};}
function youtubeId(string $url):?string{foreach(['~youtu\.be/([A-Za-z0-9_-]{11})~i','~youtube\.com/watch\?(?:[^#]*&)?v=([A-Za-z0-9_-]{11})~i','~youtube\.com/embed/([A-Za-z0-9_-]{11})~i','~youtube\.com/shorts/([A-Za-z0-9_-]{11})~i'] as $p)if(preg_match($p,$url,$m))return $m[1];return null;}
function assetUrl(string $value):string{
 $v=trim($value);if($v==='')return '';
 if(preg_match('~^https?://~i',$v))return $v;
 $v=str_replace('\\','/',ltrim($v,'/'));
 if(str_starts_with($v,'icfes_platform/'))$v=substr($v,14);
 return urlAplicacion('/'.ltrim($v,'/'));
}
function normalizarHtml(string $html):string{
 $html=trim($html);if($html==='')return '';
 $html=preg_replace(['#<script\b[^>]*>.*?</script>#is','#<style\b[^>]*>.*?</style>#is','#<object\b[^>]*>.*?</object>#is','#<embed\b[^>]*>.*?</embed>#is','/\s+on[a-z]+\s*=\s*("[^"]*"|\'[^\']*\'|[^\s>]+)/iu'],'',$html);
 $html=preg_replace('/\s+(href|src)\s*=\s*(["\'])\s*(?:javascript|vbscript|data):.*?\2/iu','',$html);
 $prev=libxml_use_internal_errors(true);$dom=new DOMDocument('1.0','UTF-8');$ok=$dom->loadHTML('<?xml encoding="UTF-8"><div id="s360root">'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);
 if($ok){$root=$dom->getElementById('s360root');
  foreach($root->getElementsByTagName('font') as $font){$parent=$font->parentNode;while($font->firstChild)$parent->insertBefore($font->firstChild,$font);$parent->removeChild($font);}
  foreach($root->getElementsByTagName('img') as $img){$src=$img->getAttribute('src');if($src)$img->setAttribute('src',assetUrl($src));$img->setAttribute('loading','lazy');$img->setAttribute('decoding','async');$img->setAttribute('style',trim($img->getAttribute('style').';max-width:100%;height:auto;'));}
  foreach($root->getElementsByTagName('iframe') as $frame){$frame->setAttribute('loading','lazy');$frame->setAttribute('allowfullscreen','allowfullscreen');$frame->setAttribute('referrerpolicy','strict-origin-when-cross-origin');}
  $out='';foreach($root->childNodes as $child)$out.=$dom->saveHTML($child);
  $html=$out;
 }libxml_clear_errors();libxml_use_internal_errors($prev);return trim($html);
}
try{
 $st=$conexion->prepare("SELECT t.id_tema,t.nombre tema,t.descripcion,t.grado,m.nombre materia FROM temas t INNER JOIN materias m ON m.id_materia=t.id_materia WHERE t.id_tema=? LIMIT 1");$st->execute([$id]);$tema=$st->fetch(PDO::FETCH_ASSOC);if(!$tema){header('Location: temas.php');exit;}
 $st=$conexion->prepare("SELECT id_contenido,contenido,estado,fecha_actualizacion FROM contenido_temas WHERE id_tema=? ORDER BY CASE WHEN estado='Borrador' THEN 0 ELSE 1 END,fecha_actualizacion DESC,id_contenido DESC LIMIT 1");$st->execute([$id]);$contenido=$st->fetch(PDO::FETCH_ASSOC)?:null;
 $st=$conexion->prepare("SELECT titulo,tipo,url,descripcion,imagen,autor,fuente,estado FROM recursos WHERE id_tema=? ORDER BY id_recurso");$st->execute([$id]);$recursos=$st->fetchAll(PDO::FETCH_ASSOC);
}catch(PDOException $ex){die('No fue posible cargar la vista previa.');}
$html=$contenido?normalizarHtml((string)$contenido['contenido']):'';
$urlTemas=urlAplicacion('/admin/contenidos/temas.php');$urlInfo=urlAplicacion('/admin/contenidos/informacion_tema.php?id='.$id);$urlEditor=urlAplicacion('/admin/contenidos/editar_tema.php?id='.$id);
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vista previa · <?=e($tema['tema'])?> | Studia360</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="<?=e(urlAplicacion('/admin/assets/studia-admin.css'))?>">
<style>
.preview-shell{max-width:1180px;margin:auto;padding:24px 18px 70px}.preview-header{border-radius:24px;background:#fff;border:1px solid #e4eaf2;padding:16px 18px;box-shadow:0 8px 24px rgba(23,32,51,.05)}.preview-hero{border-radius:25px;padding:34px;background:linear-gradient(135deg,#1d4ed8,#2563eb);color:#fff;box-shadow:0 18px 45px rgba(37,99,235,.18)}.content-card{background:#fff;border:1px solid #e4eaf2;border-radius:22px;padding:30px;box-shadow:0 10px 28px rgba(23,32,51,.05);overflow:hidden}.content-body{font-size:1.04rem;line-height:1.8;overflow-wrap:anywhere;word-break:break-word}.content-body h1,.content-body h2,.content-body h3,.content-body h4{font-weight:850;letter-spacing:-.025em;margin-top:1.5em}.content-body h1:first-child,.content-body h2:first-child,.content-body h3:first-child{margin-top:0}.content-body img{display:block;max-width:100%!important;width:auto!important;height:auto!important;margin:1rem auto;border-radius:14px}.content-body table{display:block;width:100%!important;max-width:100%;overflow-x:auto;border-collapse:collapse}.content-body td,.content-body th{padding:8px;border:1px solid #dfe6ef}.content-body iframe,.content-body video{display:block;width:100%!important;max-width:100%;min-height:360px;border:0;border-radius:14px;margin:1rem 0}.content-body pre{max-width:100%;overflow:auto;background:#f8fafc;padding:14px;border-radius:12px}.content-body a{overflow-wrap:anywhere}.resource{height:100%;border:1px solid #e4eaf2;border-radius:18px;background:#fff;padding:17px}.resource-icon{width:44px;height:44px;border-radius:13px;background:#eff6ff;color:#2563eb;display:flex;align-items:center;justify-content:center;font-size:1.2rem}.resource-link{font-size:.8rem;word-break:break-all}.empty-preview{padding:55px 20px;text-align:center;background:#f8fafc;border:1px dashed #cbd5e1;border-radius:18px}
</style></head><body>
<nav class="s360-topbar"><div class="container-fluid px-3 px-lg-4 py-2 d-flex justify-content-between align-items-center"><a class="s360-brand d-flex align-items-center gap-2" href="<?=e($urlTemas)?>"><span class="s360-brand-icon"><i class="bi bi-mortarboard-fill"></i></span>Studia360 <span class="badge text-bg-warning">Vista previa</span></a><div class="d-flex gap-2"><a class="btn btn-light border s360-btn" href="<?=e($urlInfo)?>"><i class="bi bi-pencil me-1"></i>Editar tema</a><a class="btn btn-primary s360-btn" href="<?=e($urlEditor)?>">Contenido</a></div></div></nav>
<main class="preview-shell"><section class="preview-hero mb-4"><div class="s360-kicker">Vista previa para administración</div><h1 class="h2 fw-bold mt-2 mb-2"><?=e($tema['tema'])?></h1><p class="mb-0 opacity-75"><?=e($tema['materia'])?> · <?=e($tema['grado'])?>°<?php if($tema['descripcion']):?> · <?=e($tema['descripcion'])?><?php endif;?></p></section>
<?php if($contenido):?><div class="mb-3"><span class="s360-chip <?=$contenido['estado']==='Publicado'?'success':'warning'?>"><i class="bi <?=$contenido['estado']==='Publicado'?'bi-check-circle':'bi-pencil-square'?>"></i><?=e($contenido['estado'])?></span> <span class="small text-secondary ms-2">Última actualización: <?=e(date('d/m/Y H:i',strtotime($contenido['fecha_actualizacion'])))?></span></div><?php endif;?>
<div class="row g-4"><div class="col-lg-8"><section class="content-card"><?php if($html):?><article class="content-body"><?=$html?></article><?php else:?><div class="empty-preview"><div class="s360-iconbox mx-auto mb-3"><i class="bi bi-file-earmark-text"></i></div><h2 class="h5 fw-bold">Este tema todavía no tiene contenido</h2><p class="s360-muted mb-0">Puedes construir la lección desde el editor de contenido.</p></div><?php endif;?></section></div>
<aside class="col-lg-4"><section class="s360-card p-4 mb-4"><div class="s360-section-title mb-3">Ficha del tema</div><div class="mb-3"><small class="s360-muted">Materia</small><div class="fw-bold"><?=e($tema['materia'])?></div></div><div class="mb-3"><small class="s360-muted">Grado</small><div class="fw-bold"><?=e($tema['grado'])?>°</div></div><div><small class="s360-muted">Recursos</small><div class="fw-bold"><?=count($recursos)?></div></div></section></aside></div>
<?php if($recursos):?><section class="mt-5"><div class="mb-3"><div class="s360-section-title">Recursos complementarios</div><div class="small s360-muted">Así se verán los recursos asociados al tema.</div></div><div class="row g-3"><?php foreach($recursos as $r):$img=assetUrl((string)($r['imagen']??''));if(!$img&&strtolower((string)$r['tipo'])==='video'&&($yt=youtubeId((string)$r['url'])))$img='https://img.youtube.com/vi/'.rawurlencode($yt).'/hqdefault.jpg';?><div class="col-md-6 col-xl-4"><article class="resource"><div class="d-flex gap-3 mb-3"><div class="resource-icon"><i class="bi <?=e(recursoIcon((string)$r['tipo']))?>"></i></div><div><h3 class="h6 fw-bold mb-1"><?=e($r['titulo'])?></h3><span class="small text-secondary"><?=e(ucfirst((string)$r['tipo']))?></span></div></div><?php if($r['descripcion']):?><p class="small text-secondary"><?=e($r['descripcion'])?></p><?php endif;?><a class="resource-link text-decoration-none" href="<?=e($r['url'])?>" target="_blank" rel="noopener noreferrer">Abrir recurso <i class="bi bi-box-arrow-up-right"></i></a></article></div><?php endforeach;?></div></section><?php endif;?>
</main></body></html>
