<?php
declare(strict_types=1);
require_once __DIR__ . '/../../includes/seguridad.php';
exigirAdmin();
function e($v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }

try {
    $avatares=$conexion->query("SELECT a.*,COUNT(u.id_usuario) AS usuarios_con_avatar FROM avatares a LEFT JOIN usuarios u ON u.id_avatar=a.id_avatar GROUP BY a.id_avatar ORDER BY a.puntos_requeridos,a.id_avatar")->fetchAll(PDO::FETCH_ASSOC);
    $insignias=$conexion->query("SELECT i.*,COUNT(ui.id_usuario) AS usuarios_con_insignia FROM insignias i LEFT JOIN usuarios_insignias ui ON ui.id_insignia=i.id_insignia GROUP BY i.id_insignia ORDER BY i.id_insignia")->fetchAll(PDO::FETCH_ASSOC);
    $usuarios=(int)$conexion->query("SELECT COUNT(*) FROM usuarios WHERE id_rol=(SELECT id_rol FROM roles WHERE nombre='Estudiante' LIMIT 1) AND estado='Activo'")->fetchColumn();
    $desbloqueos=(int)$conexion->query("SELECT COUNT(*) FROM usuarios_insignias")->fetchColumn();
} catch(Throwable $e) { $avatares=[];$insignias=[];$usuarios=0;$desbloqueos=0; }
$activosA=count(array_filter($avatares,fn($a)=>$a['estado']==='Activo'));
$activosI=count(array_filter($insignias,fn($i)=>$i['estado']==='Activa'));
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Coleccionables | Studia360</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><style>
body{background:radial-gradient(circle at top right,rgba(124,58,237,.08),transparent 28%),#f4f7fb;color:#26364a}.top{background:linear-gradient(105deg,#173f80,#2467c5)}.hero{border-radius:25px;padding:2rem;color:#fff;background:linear-gradient(120deg,#5b21b6,#2467c5);box-shadow:0 18px 42px rgba(54,46,120,.14)}.cardx{background:#fff;border:1px solid #dce5f0;border-radius:22px;box-shadow:0 10px 28px rgba(31,57,92,.06)}.item{height:100%;border:1px solid #e2e8f0;border-radius:18px;padding:1.15rem;background:linear-gradient(180deg,#fff,#fafbff)}.icon{width:58px;height:58px;border-radius:17px;background:#f1ebff;color:#6d35d4;display:flex;align-items:center;justify-content:center;font-size:1.55rem}.stat{padding:1.1rem;border:1px solid #dce5f0;border-radius:18px;background:#fff;height:100%}.stat strong{font-size:1.6rem}.muted{color:#718096}.badge-soft{background:#eef5ff;color:#2467c5;border:1px solid #d9e8ff}.img-preview{width:64px;height:64px;border-radius:16px;object-fit:cover;background:#eef2f7;border:1px solid #dce5f0}
</style><link rel="stylesheet" href="<?= htmlspecialchars(urlAplicacion('/admin/assets/studia-admin.css'), ENT_QUOTES, 'UTF-8') ?>">
</head><body><nav class="navbar navbar-dark top"><div class="container py-2"><a class="navbar-brand fw-bold" href="<?=e(urlAplicacion('/admin/dashboard.php'))?>"><i class="bi bi-mortarboard-fill me-2"></i>Studia360 <span class="badge bg-light text-primary">Admin</span></a><div class="d-flex gap-2"><a class="btn btn-outline-light btn-sm" href="<?=e(urlAplicacion('/admin/gamificacion/index.php'))?>">Configurar</a><a class="btn btn-light btn-sm" href="<?=e(urlAplicacion('/admin/dashboard.php'))?>">Dashboard</a></div></div></nav>
<main class="container py-4 py-lg-5"><section class="hero mb-4"><div class="d-flex justify-content-between align-items-center flex-wrap gap-4"><div><div class="small text-uppercase fw-bold opacity-75 mb-2">Personalización y recompensas</div><h1 class="h2 fw-bold mb-2">Coleccionables</h1><p class="mb-0 text-white-50">Consulta el catálogo de avatares e insignias y observa cómo se están utilizando entre los estudiantes.</p></div><i class="bi bi-stars display-4"></i></div></section>
<div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="stat"><div class="muted small">Avatares activos</div><strong><?=$activosA?></strong></div></div><div class="col-6 col-lg-3"><div class="stat"><div class="muted small">Insignias activas</div><strong><?=$activosI?></strong></div></div><div class="col-6 col-lg-3"><div class="stat"><div class="muted small">Estudiantes</div><strong><?=$usuarios?></strong></div></div><div class="col-6 col-lg-3"><div class="stat"><div class="muted small">Insignias obtenidas</div><strong><?=$desbloqueos?></strong></div></div></div>
<section class="cardx p-4 mb-4"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h2 class="h5 fw-bold mb-1">Avatares</h2><p class="muted small mb-0">Elementos de personalización desbloqueables según los puntos acumulados.</p></div><a href="<?=e(urlAplicacion('/admin/gamificacion/index.php'))?>#avatares" class="btn btn-outline-primary btn-sm"><i class="bi bi-pencil me-1"></i>Administrar avatares</a></div><div class="row g-3"><?php foreach($avatares as $a):?><div class="col-md-6 col-xl-4"><article class="item"><div class="d-flex gap-3 align-items-center mb-3"><div class="icon"><i class="bi bi-person-badge-fill"></i></div><div><h3 class="h6 fw-bold mb-1"><?=e($a['nombre'])?></h3><span class="badge rounded-pill <?=$a['estado']==='Activo'?'text-bg-success':'text-bg-secondary'?>"><?=e($a['estado'])?></span></div></div><div class="d-flex justify-content-between small mb-1"><span class="muted">Desbloqueo</span><strong><?=number_format((int)$a['puntos_requeridos'])?> XP</strong></div><div class="d-flex justify-content-between small"><span class="muted">Usuarios que lo tienen seleccionado</span><strong><?=number_format((int)$a['usuarios_con_avatar'])?></strong></div></article></div><?php endforeach;?><?php if(!$avatares):?><div class="col-12 text-center muted py-4">No hay avatares configurados.</div><?php endif;?></div></section>
<section class="cardx p-4"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h2 class="h5 fw-bold mb-1">Insignias</h2><p class="muted small mb-0">Recompensas que se otorgan automáticamente cuando el estudiante cumple su criterio.</p></div><a href="<?=e(urlAplicacion('/admin/gamificacion/index.php'))?>#insignias" class="btn btn-outline-primary btn-sm"><i class="bi bi-pencil me-1"></i>Administrar insignias</a></div><div class="row g-3"><?php foreach($insignias as $i):?><div class="col-md-6 col-xl-4"><article class="item"><div class="d-flex gap-3 align-items-center mb-3"><div class="icon"><i class="bi bi-award-fill"></i></div><div><h3 class="h6 fw-bold mb-1"><?=e($i['nombre'])?></h3><span class="badge rounded-pill <?=$i['estado']==='Activa'?'text-bg-success':'text-bg-secondary'?>"><?=e($i['estado'])?></span></div></div><p class="small muted mb-3"><?=e($i['descripcion'] ?: 'Sin descripción configurada.')?></p><div class="d-flex justify-content-between small mb-1"><span class="muted">Criterio</span><strong><?=e($i['criterio'] ?: 'Sin criterio')?></strong></div><div class="d-flex justify-content-between small"><span class="muted">Estudiantes que la obtuvieron</span><strong><?=number_format((int)$i['usuarios_con_insignia'])?></strong></div></article></div><?php endforeach;?><?php if(!$insignias):?><div class="col-12"><div class="text-center py-5 muted"><i class="bi bi-award display-5 d-block mb-2"></i><strong>No hay insignias creadas todavía.</strong><p class="mb-0">Puedes configurarlas desde el módulo de gamificación.</p></div></div><?php endif;?></div></section>
</main></body></html>
